# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

orbs:
  go: circleci/go@1.7.3

jobs:
  build:
    executor:
      name: go/default
      tag: '1.23.3'
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: sudo apt-get --allow-releaseinfo-change update && sudo apt-get install -y libgtk-3-dev libasound2-dev
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
      - run: go get -v -t -d ./...
      - run: go build .
      - run: xvfb-run --auto-servernum go test -v -race ./...
      - run: golangci-lint run ./...
workflows:
  version: 2
  build:
    jobs:
      - build
